version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: complaint
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8181:8181"
    volumes:
      - ./backend/files:/app/files
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  apache:
    image: httpd:2.4
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
